var scrnX = screenX;
var inWid = innerWidth;
var scrnL = screenLeft;
var inHet = innerHeight;

document.write('<table>');
		document.write('<tr>');
				document.write('<td>');
						document.write("screenX");
				document.write('</td>');
				document.write('<td>');
						document.write(scrnX);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("innerWidth");
				document.write('</td>');
				document.write('<td>');
						document.write(inWid);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("screenLeft");
				document.write('</td>');
				document.write('<td>');
						document.write(scrnL);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("innerHeight");
				document.write('</td>');
				document.write('<td>');
						document.write(inHet);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("location");
				document.write('</td>');
				document.write('<td>');
						document.write(location);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("screen.availWidth");
				document.write('</td>');
				document.write('<td>');
						document.write(screen.availWidth);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("color Depth");
				document.write('</td>');
				document.write('<td>');
						document.write(screen.colorDepth);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("screen.orientation");
				document.write('</td>');
				document.write('<td>');
						document.write(screen.orientation);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("history");
				document.write('</td>');
				document.write('<td>');
						document.write(history);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("navigator");
				document.write('</td>');
				document.write('<td>');
						document.write(navigator);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("userAgent");
				document.write('</td>');
				document.write('<td>');
						document.write(navigator.userAgent);
				document.write('</td>');
		document.write('</tr>');
		document.write('<tr>');
				document.write('<td>');
						document.write("online");
				document.write('</td>');
				document.write('<td>');
						document.write(navigator.onLine);
				document.write('</td>');
		document.write('</tr>');
document.write('</table>');








